networks:
  go:
    driver: bridge

volumes:
  goroot:
  gocache:
  pgdata:

services:
  app:
    container_name: app
    image: golang:1.22-alpine
    volumes:
      - .:/app
    environment:
      - PORT=8080
      - KEY=s!gningK3y###
      - SALT=5@lt!!!
    working_dir: /app
    ports:
      - 8080:8080
    command:
      - tail
      - -f
      - /etc/hosts
    networks:
      go:
        aliases:
          - app
    depends_on:
      - pgsql_db

  pgsql_db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgsql_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      go:
        aliases:
          - pgsql_db

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - URL=/docs/swagger.yaml
    volumes:
      - ./docs:/usr/share/nginx/html/docs
    ports:
      - 8084:8080